version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: seagulendar_admin
      POSTGRES_PASSWORD: seagull
      POSTGRES_DB: seagulendar_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
