version: '3.8'

services:
  seagulendar_server:
    image: seagulendar_server:latest
    restart: unless-stopped
    container_name: seagulendar_server
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - seagull-db
    environment:
      - DATABASE_URL=postgres://postgres:seaguLl@seagull-db:5432/seagull-db
      - PORT=3000
    ports:
      - "3000:3000"
    networks:
      - seagull-network

  seagull-db:
    container_name: seagull-db
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: seaguLl
      POSTGRES_DB: seagull-db
    networks:
      - seagull-network
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5433:5432'

  seagulendar_client:
    image: seagulendar_client:latest
    restart: unless-stopped
    container_name: seagulendar_client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ./client/dist:/usr/share/nginx/html
    networks:
      - seagull-network
  
networks: 
  seagull-network:
    name: seagull-network
    driver: bridge
